---
Title: "Project Blog"
---

Assisted Reproductive Technology (ART) regression analysis and user application blog:

# Week 1:

This first week was the initial planning stage outlining the subject matter of the project and what I want the end product to show in terms of skill and exploration.

# Week 2:

What did you do last week?

Last week I explored the direction I plan to go with my project, specifically creating a rough timeline and achievable goals. I'm still homing in on what is achievable with a wants v. needs type of approach. I plan to create a predictive model starting with one feature then expanding it. My priority is the backend workings of the model then linking it to a simple frontend design

What do you plan to do this week?

This week I plan to setup my website and do more research on applicable techniques as well as review my dataset and transforming it into usable information

Are there any impediments in your way?

Just myself, after a long break and this being my final semester it's been a slower ramp up than in the past but I'm simply focusing on doing one thing at a time. The short week and crazy snow storm had my week not really matching up with course schedules.

Reflection on the process you used last week, how can you make the process work better?

There wasn't much of a structured process last week, it was more so just doing some thinking and cursory google searches. I'm creating a little checklist of tasks this week to ramp back up into an efficient working setup.

# Week 3:

What did you do last week?

I completed the project proposal rough draft and decided on the specific frameworks I’ll be using for each person. I will be primarily using Flask, Python based modules, and SQLite. I did some preliminary data cleaning and identified the attributes with the best backing data.

 

What do you plan to do this week?

This week I plan to do some initial data transformation and exploration just to get in the flow of building this project. Additionally, I plan to set up my frontend Flask template to start a front-to-back approach to the application. I also plan to format my site.

Are there any impediments in your way?

Not particularly, time mostly. I think continuing to work on the steps I identified in the initial planning stage will help build momentum.

Reflection on the process you used last week, how can you make the process work better?

I spent a little too much time in the contemplation stage last week and this week I plan to take more action. Putting together the rough version of my frontend will motivate me to work on it once I see how ugly it is initially. Time is always a factor but I have put together a work/rest schedule for myself this weekend.

# Week 4:

What did you do last week?

Last week I finished the project proposals and reviewed the feedback I received to better home in on my project. Additionally, I began laying the foundation for the UI and some data preprocessing.

What do you plan to do this week?

This week I implemented a login page and database for users as well as laying the ground-work for my users attributes database. I used Flask for the front-end and SQLite for the database. I initially wrote the front-end in with simple logic and template rendering with placeholder names. Additionally, I got some free templates online and started to plug them in to my existing code.

Are there any impediments in your way?

This was a weird week and I was working without internet access for most of it which made some of the issues I ran into harder to solve. The upcoming week will be much more productive

Reflection on the process you used last week, how can you make the process work better?

My process last week was to simply do what I could given the circumstances. Next week should be much more normal and will allow me to utilize available resources much better. My small issues were solved by looking at previous code bases on my machine.

# Week 5:

What did you do last week?

I implemented a login page with a connected local database for simple login querying. As it is low on my priority list it's moreso the minimal needed to make the app work. I'm currently using a plan of creating a prototype app from front to back, then developing in a greater scope from back to front. 

What do you plan to do this week?

This week I need to focus on getting my website up and running, but this weekend I plan to do some heavy lifting on the dashboard and linking my analytical code to one or more features in the dashboard. Users entering values then getting a return value from my code for a single feature would be the benchmark by the end of the week.

Are there any impediments in your way?

No, considering last week wasn't as productive as I would have liked I have allocated more time to schoolwork this week. I have clear vision of what I want the application to look like by the end of the week and have drawn out a roadmap with bullet points of what I need for each benchmark.

Reflection on the process last week and how can I make it better?

Last week my process wasn't structured enough. This week I have a distinct plan both in my time and a roadmap for what I want accomplished and how I will do it.

# Week 6:

What did you do last week?

Last week I created my website and creating essentially a condensed and readable linkedin profile hosted through GitHub. This website still needs some polishing before I would submit it on an application but for now it's a very good starting point. Additionally, I caught back up after losing some work last week and recovered nearly all of it. This included frontend code as well as database code. 

What do you plan to do this week?

This week I plan to accomplish what I was supposed to the week before. Implementing my dashboard and creating my data pipeline by calling my python code based on my user inputs/SQL database and generating a value. I'm looking to start with some simple graphs, but would also like to generate the specific data I'm looking to provide users: expected # of artificial reproductive cycles for their attributes.

Are there any impediments in your way?

There are no impediments in my way outside of having a heavy workload for another class this week and having to recover lost work last week. I'm still a little behind but I still feel on track to complete a prototype by the end of the course.

Reflection on the process you used last week, how can you make the process work better?

My process was more refined as I felt focus honed by finding that much of my work that had been done already simply wasn't there. I already have a schedule for this weekend by hour with built in breaks to work on this project.

# Week 7:

Project Overview:

This project is a combination of application development and regression modeling construction. Using publicly available data from the Center for Disease control the application will take input from users and run them through the model to determine their predicted success rate based on the chosen parameters. Specifically, this application is based on Artificial Reproductive Technology and is meant to provide user guidance for those in the contemplative stage of seeking medical advice. This tool looks to provide useful information based on the users characteristics such as: estimated cost, success rate stratification on a categorical scale, and expected number of attempts to achieve a live-birth. From the frontend to the backend and all analytical logic is provided by the author. 

 

Goals:

Frontend Design:

Login page: users should be able to register and login to store results 

Dashboard: users should be able to input their attributes based on the available drop-down values and receive a processed return value

Graph: graphical trends for different attributes with users able to input different attributes to produce different trendlines

 

Backend Design:

Database: using SQL user information should be stored and able to be queried

Analysis: Exploratory data analysis performed on the publicly available data and regression model linked to the frontend to perform live analysis

 

Accomplishments so far:

Login page and database configured with test values and appropriately redirects to the dashboard upon successful login

Database is stored as a local file for now as appropriate for the proxy environment

Dashboard page is appropriately linked with the python data analysis code

Initial and intermediate exploratory data analysis has been completed

Established environment files for streamlined launching of the application

 

These accomplishments have established the flow of data for this project and serve as the foundation for some more advanced undertakings. Now that there is a minimally working product more advanced portions can be developed. 

 

To do:

Research on the regression modeling to be used

Implementing the regression model

Encrypting user login and password information

Polishing the frontend

Developing the database to store more values

Linking graphs to the frontend

Research estimated costs and produce values based on user input

 

Reflection:

 
Progress hasn’t been linear for this project as expected. Moreso, the amount of time it takes to develop every little portion of this project has surpassed expectations but still remains within reach of the time constraints. To reach the remaining goals for this project is simply to follow the list of remaining features to be implemented as laid out in a priority list of most to least important. The existing scheduling for this project has been adequate. 

# Week 8:

What did you do last week?

Last week I got my pipeline fully connected and tested with some simple functions and values passed to my frontend. I also did some further planning on the aspects of the linear regression model I will be implementing as well as doing some organizational work on my code base.

What do you plan to do this week?

This week I plan to flush out my regression model and its aspects more concretely by writing out the bootstrapping methodology, RMSE calculation,  and linear regression model. Furthermore, I plan to write in the remaining attribute values as well as add more than the few test ones I implemented to test the pipeline.

Are there any impediments in your way?

There are no impediments in my way.

Reflection on the process you used last week, how can you make the process work better?

My process last week worked just fine, I will continue to use the same measured approach by working on the project one little step at a time. 

# Week 9:

What did you do last week?

Last week I wrote the code for my bootstrap, linear regression, and RMSE function. I linked them through to my front end and was able to pass my selections from the frontend, to my functions, and return values to my frontend

What do you plan to do this week?

This week I intend to spend time lowering the RMSE through attribute selection and value transformation. Additionally I plan to go over my initial EDA to ensure that the data is cleaned and processed effectively to ensure I'm getting the most accurate results

Are there any impediments in your way?

I have a weird work week coming up with lots of hours so I may not have as much time to work through the project on the specific days I usually do.

Reflection on the process you used last week, how can you make the process work better?

Last week I created my task list and accomplished it. I wouldn't change anything about it. I do anticipate taking some time to clean up my code base as it isn't the most organized at this time.

# Week 10:

What did you do last week?

Last week I explored some Linkedin Learning processes and tidied up some of my original data cleaning from the beginning of the project. Additionally, I looked into some possible options for enhancing the reliability of my data especially for small sample sizes. Something I find interesting and am looking to possibly implement is Multiple Imputation by Chained Equations.

What do you plan to do this week?

This week I plan to split my time between trying to implement MICE and performing some of the transformations on my data which will require some extensive graphing between attributes and additional work. I see this as continuing for the next week or so. 

Are there any impediments in your way?

Time as always.

Reflection on the process you used last week, how can you make the process work better?

I feel confident in my process so far and feel comfortable with my to do list. As I realize this project is ending soon I have allocated the remaining weeks to include my regression work for the next nearly, shoring up my front-end presentation, and then getting the final presentation in order

# Week 11:

What did you do last week?

Last week I explored different techniques to attempt to reduce my RMSE, I tried testing the interaction between two features and if their relationship would help the predictive ability of my model. I applied a logit transformation on the target variable to map the bounded success rate into an unbounded space. Training on the transformed values and mapping them back using the inverse sigmoid function did not improve RMSE. Both proved fruitless in the sense that my RMSE actually either got worse or remained unchanged, however this was actually a very insightful result. This meets the intent of my project well in terms of exploring linear regression and using some statistical analysis gave me some interesting insights. I will likely try to simply add one more attribute before tightening up the project and getting the write up together. The implementation of the attribute combination and logit transformation was time consuming as well as recording the results along the way.

What do you plan to do this week?

Tighten up my project for presentability and turn my notes into a presentable analysis

Are there any impediments in your way?

No, I wish the things I tried would have produced a result that improved my values, but it was still fruitful to see what didn't work or didn't change. Sometimes that's just as valuable especially as a learning medium

Reflection on the process you used last week, how can you make the process work better?

The process I used last week was to pick something I wanted to try, research, implement, and analyze. It worked well.

# Week 12:

What did you do last week?

Last week I polished my project a little and focused on tightening up the presentation of my project.

What do you plan to do this week?

Write up my final presentation and ensure my website is updated and code is working as intended.

Are there any impediments in your way?

No.

Reflection on the process you used last week, how can you make the process work better?

My process last week was to simply work on the project and make it look nicer. I will continue to use the same process this week as well as allocating some time to writing up my presentation.

# Week 13:

[Download/View PDF](Project_Final.pdf)